(function(global){
'use strict';

const currentLanguage=()=>global.hhGetLanguage?.()||(()=>{try{return localStorage.getItem('hh-lang')||'ar'}catch(_){return 'ar'}})();

const ARABIC_DIGITS={'٠':'0','١':'1','٢':'2','٣':'3','٤':'4','٥':'5','٦':'6','٧':'7','٨':'8','٩':'9'};

// Long phrases come first. The goal is presentation purity, not changing routes,
// identifiers or business-domain keys used internally by the demo.
const toArabic=[
  ['Dawwar Pilot','نسخة دوّر التجريبية'],
  ['Pilot MVP','النسخة التجريبية الأولى'],
  ['Pilot-first workspace','مساحة عمل تبدأ بالنسخة التجريبية'],
  ['Interactive Product Demo','عرض تفاعلي للمنتج'],
  ['Product Vision','رؤية المنتج'],
  ['Future Vision','الرؤية المستقبلية'],
  ['Business Story','قصة العمل'],
  ['Business model','نموذج العمل'],
  ['Business Model','نموذج العمل'],
  ['Launch revenue','إيراد الإطلاق'],
  ['Not launch scope','خارج نطاق الإطلاق'],
  ['Launch Scope','نطاق الإطلاق'],
  ['Customer promise','وعدنا للعميل'],
  ['Venue promise','وعدنا للقاعة'],
  ['trusted venue marketplace','سوق موثوق للقاعات'],
  ['Availability first','التوافر أولًا'],
  ['Availability-first','التوافر أولًا'],
  ['Real-time Venue Availability + Booking + Venue Management.','توافر القاعات والحجز وإدارة القاعات في مكان واحد.'],
  ['Mock data · No backend · Presentation demo','بيانات تجريبية · بدون خادم خلفي · عرض توضيحي'],
  ['Demo only','عرض تجريبي فقط'],
  ['Demo Guide','دليل العرض التجريبي'],
  ['Demo Mode','وضع العرض التجريبي'],
  ['Demo Scenario','سيناريو العرض التجريبي'],
  ['Recommended story','المسار المقترح'],
  ['Request-to-Book','طلب حجز'],
  ['Request booking','طلب حجز'],
  ['request-to-book','طلب حجز'],
  ['Source attribution','تحديد مصدر الحجز'],
  ['Customer confirmation','تأكيد العميل'],
  ['Venue confirmation','تأكيد القاعة'],
  ['Booking attribution','تحديد مصدر الحجز'],
  ['Commission reconciliation','تسوية العمولات'],
  ['Success commission','عمولة النجاح'],
  ['Commission only','عمولة عند النجاح فقط'],
  ['success commission','عمولة النجاح'],
  ['Commission statement','كشف العمولات'],
  ['Venue commission statement','كشف عمولات القاعة'],
  ['Platform-sourced','قادمة من المنصة'],
  ['platform-sourced','قادمة من المنصة'],
  ['Qualified lead','عميل محتمل مؤهل'],
  ['Qualified leads','عملاء محتملون مؤهلون'],
  ['Open leads','عملاء محتملون مفتوحون'],
  ['New Lead','عميل محتمل جديد'],
  ['New lead','عميل محتمل جديد'],
  ['Leads CRM','إدارة العملاء المحتملين'],
  ['Lead Pipeline','مسار العملاء المحتملين'],
  ['Lead Response SLA','زمن الاستجابة للعملاء المحتملين'],
  ['Visit Scheduled','زيارة محددة'],
  ['Offer / Hold','عرض / حجز مؤقت'],
  ['Quick Booking','حجز سريع'],
  ['Offline Booking','حجز خارجي'],
  ['Online Booking','حجز إلكتروني'],
  ['Online + offline','إلكتروني + خارجي'],
  ['online + offline','إلكتروني + خارجي'],
  ['online and offline','الإلكتروني والخارجي'],
  ['online inventory','المخزون الإلكتروني'],
  ['offline inventory','المخزون الخارجي'],
  ['online availability','التوافر الإلكتروني'],
  ['offline availability','التوافر الخارجي'],
  ['Online Payment','الدفع الإلكتروني'],
  ['Online deposit','العربون الإلكتروني'],
  ['online deposit','العربون الإلكتروني'],
  ['Payment orchestration','إدارة عمليات الدفع'],
  ['payment orchestration','إدارة عمليات الدفع'],
  ['Transaction layer','طبقة المعاملات'],
  ['Atomic hold','حجز مؤقت محمي من التعارض'],
  ['hard holds','الحجوزات المؤقتة الملزمة'],
  ['Hard Hold','حجز مؤقت ملزم'],
  ['Refund / payout orchestration','إدارة الاستردادات ومستحقات القاعات'],
  ['Refunds / Payouts','الاستردادات / مستحقات القاعات'],
  ['Bookings & Payments','الحجوزات والمدفوعات'],
  ['Packages & Pricing','الباقات والأسعار'],
  ['Dynamic Pricing Rules','قواعد التسعير الديناميكي'],
  ['Dynamic Pricing','التسعير الديناميكي'],
  ['Premium analytics','تحليلات متقدمة'],
  ['Marketplace Intelligence','تحليلات السوق'],
  ['Marketplace Health','صحة السوق'],
  ['Platform Overview','نظرة عامة على المنصة'],
  ['Platform Admin','إدارة المنصة'],
  ['Venue Operations','تشغيل القاعات'],
  ['Verification queue','طابور التحقق'],
  ['Verification checks','فحوصات التحقق'],
  ['Calendar Health','صحة التقويم'],
  ['Calendar Health Score','درجة صحة التقويم'],
  ['Availability Reliability','موثوقية التوافر'],
  ['Availability Sync','مزامنة التوافر'],
  ['Stale availability','توافر قديم'],
  ['Fresh availability','توافر حديث'],
  ['Recently updated','محدّث حديثًا'],
  ['All systems operational','كل الأنظمة تعمل'],
  ['Demand heatmap','خريطة الطلب'],
  ['Supply gap','فجوة العرض'],
  ['Lost revenue','إيراد مفقود'],
  ['Lost demand','طلب مفقود'],
  ['Revenue Intelligence','ذكاء الإيرادات'],
  ['Business Intelligence','ذكاء الأعمال'],
  ['Action Center','مركز الإجراءات'],
  ['Pricing Simulator','محاكي الأسعار'],
  ['Strategic Simulator','المحاكي الاستراتيجي'],
  ['Flexible Dates','تواريخ مرنة'],
  ['Family Shortlist','قائمة الأسرة المختصرة'],
  ['Reverse Marketplace','السوق العكسي'],
  ['Request Offers','اطلب عروضًا'],
  ['Last-minute inventory','تواريخ متاحة في اللحظة الأخيرة'],
  ['Live availability','توافر مباشر'],
  ['Live deal simulation','محاكاة عرض مباشر'],
  ['Smart booking','حجز ذكي'],
  ['Smart alternative','بديل ذكي'],
  ['Best value','أفضل قيمة'],
  ['Peak demand date','يوم مرتفع الطلب'],
  ['Venue lead source','مصدر العميل المحتمل'],
  ['Venue-side idea','فكرة لصاحب القاعة'],
  ['Qualified supply only','قاعات مناسبة فقط'],
  ['Offer expiry','صلاحية العرض'],
  ['Offer comparison','مقارنة العروض'],
  ['Content Quality','جودة المحتوى'],
  ['Content quality','جودة المحتوى'],
  ['Conversion Lift','تحسن التحويل'],
  ['Tour Quality Score','درجة جودة الجولة'],
  ['Tour Completion','اكتمال الجولة'],
  ['Multiple Scenes','مشاهد متعددة'],
  ['Hotspot Management','إدارة نقاط المعلومات'],
  ['Coverage Checklist','قائمة اكتمال التغطية'],
  ['Revenue per Available Date','الإيراد لكل تاريخ متاح'],
  ['Package Profitability','ربحية الباقات'],
  ['Cash-flow Forecast','توقع التدفق النقدي'],
  ['Outstanding Receivables','مبالغ مستحقة التحصيل'],
  ['Contribution Margin','هامش المساهمة'],
  ['Contribution Profit','ربح المساهمة'],
  ['Operating Profit','الربح التشغيلي'],
  ['Profit Margin','هامش الربح'],
  ['Revenue Mix','مزيج الإيرادات'],
  ['Customer CAC','تكلفة اكتساب العميل'],
  ['Customer LTV','قيمة العميل'],
  ['Venue Acquisition Cost','تكلفة اكتساب القاعة'],
  ['Venue Payback','مدة استرداد تكلفة القاعة'],
  ['Zero-result Search','البحث بلا نتائج'],
  ['Payment Failure Rate','نسبة فشل الدفع'],
  ['Availability Mismatch Rate','نسبة عدم تطابق التوافر'],
  ['Cancellation Rate','نسبة الإلغاء'],
  ['Refund Rate','نسبة الاسترداد'],
  ['Dispute Rate','نسبة النزاعات'],
  ['SLA Breaches','تجاوزات زمن الخدمة'],
  ['Customer pilot','رحلة العميل التجريبية'],
  ['Pilot Ops','تشغيل النسخة التجريبية'],
  ['Admin / Ops Pilot','إدارة وتشغيل النسخة التجريبية'],
  ['VenueOS Lite','إدارة القاعات المبسطة'],
  ['VenueOS Pro','إدارة القاعات الاحترافية'],
  ['VenueOS','نظام إدارة القاعات'],
  ['Marketplace','السوق'],
  ['Monetization','تحقيق الإيرادات'],
  ['Differentiation','ميزة تنافسية'],
  ['production events','بيانات تشغيل فعلية'],
  ['core funnel','مسار التحويل الأساسي'],
  ['ROI','العائد التشغيلي'],
  ['configurable/versioned','قابلة للتعديل والإصدار'],
  ['configurable','قابلة للتعديل'],
  ['hard-coded','مثبتة داخل النظام'],
  ['attribution','تحديد المصدر'],
  ['reconciliation','التسوية'],
  ['freshness','حداثة البيانات'],
  ['payments','المدفوعات'],
  ['Payments','المدفوعات'],
  ['refunds','الاستردادات'],
  ['Refunds','الاستردادات'],
  ['payouts','مستحقات القاعات'],
  ['Payouts','مستحقات القاعات'],
  ['subscription','اشتراك'],
  ['Subscription','اشتراك'],
  ['Commission','العمولة'],
  ['commission','العمولة'],
  ['Enquiry','استفسار'],
  ['enquiry','استفسار'],
  ['Quote','عرض سعر'],
  ['quote','عرض سعر'],
  ['Lead','عميل محتمل'],
  ['lead','عميل محتمل'],
  ['Leads','عملاء محتملون'],
  ['leads','عملاء محتملون'],
  ['Calendar','التقويم'],
  ['Bookings','الحجوزات'],
  ['Booking','الحجز'],
  ['Visits','الزيارات'],
  ['Visit','زيارة'],
  ['Search','البحث'],
  ['Shortlist','القائمة المختصرة'],
  ['Compare','مقارنة'],
  ['Checkout','إتمام الحجز'],
  ['Availability','التوافر'],
  ['Available','متاح'],
  ['Booked','محجوز'],
  ['Confirmation needed','تأكيد مطلوب'],
  ['Confirmed','مؤكد'],
  ['Customer','العميل'],
  ['Venue Owner','صاحب القاعة'],
  ['Venue','القاعة'],
  ['Investor','المستثمر'],
  ['Admin','الإدارة'],
  ['Analytics','التحليلات'],
  ['Revenue','الإيرادات'],
  ['Occupancy','نسبة الإشغال'],
  ['Conversion','التحويل'],
  ['Status','الحالة'],
  ['Details','التفاصيل'],
  ['Home','الرئيسية'],
  ['Explore','استكشف'],
  ['Account','الحساب'],
  ['Guide','الدليل'],
  ['Reset Demo','إعادة العرض التجريبي'],
  ['Pilot','النسخة التجريبية'],
  ['Demo','عرض تجريبي'],
  ['MVP','النسخة الأولى'],

  // Venue and package display names are localized in Arabic mode.
  ['Royal Garden','رويال جاردن'],
  ['Luma Hall','لوما هول'],
  ['Nile Palace','نايل بالاس'],
  ['Garden 37','جاردن 37'],
  ['Palm Palace','بالم بالاس'],
  ['Lake House','ليك هاوس'],
  ['Wedding Plus','باقة الزفاف المميزة'],
  ['Hall Only','القاعة فقط'],
  ['Signature','الباقة الخاصة'],

  // Venue attributes.
  ['Bridal room','غرفة العروس'],
  ['Large stage','مسرح كبير'],
  ['Nile view','إطلالة على النيل'],
  ['Lake view','إطلالة على البحيرة'],
  ['Outdoor','خارجي'],
  ['Indoor','داخلي'],
  ['Parking','موقف سيارات'],
  ['Stage','مسرح'],
  ['Garden','حديقة'],
  ['Sound','نظام صوت'],
  ['Valet','خدمة صف السيارات'],
  ['Buffet','بوفيه'],
  ['Decoration','تجهيزات وزينة'],

  // Demo people: intentionally not Karim/Aya.
  ['Karim & Aya','محمود وسلمى'],
  ['كريم وآية','محمود وسلمى'],
  ['Mona & Ali','منى وعلي'],
  ['Omar & Mariam','عمر ومريم'],
  ['Nour & Ahmed','نور وأحمد'],
  ['Sara & Mostafa','سارة ومصطفى'],
  ['Hana & Youssef','هنا ويوسف'],
  ['Yara & Adam','يارا وآدم'],

  // Locations and common labels.
  ['New Cairo','القاهرة الجديدة'],
  ['Sheikh Zayed','الشيخ زايد'],
  ['Nasr City','مدينة نصر'],
  ['Maadi','المعادي'],
  ['October','أكتوبر'],
  ['September','سبتمبر'],
  ['Guests','الضيوف'],
  ['guests','ضيوف'],
  ['Budget','الميزانية'],
  ['Date','التاريخ'],
  ['Area','المنطقة'],
  ['Event type','نوع المناسبة'],
  ['Wedding','زفاف'],
  ['Engagement','خطوبة'],
  ['Corporate event','مناسبة شركات'],
  ['Starting price','سعر مبدئي'],
  ['Final venue value','القيمة النهائية للقاعة'],
  ['Deposit','العربون'],
  ['Received','تم الاستلام'],
  ['DUE','مستحقة'],
  ['Won','تم الحجز'],
  ['Pending enquiries','استفسارات معلقة'],
  ['Verified venues','قاعات موثقة'],
  ['Verified venue','قاعة موثقة'],
  ['Verified','موثقة'],
  ['Fresh','حديث'],
  ['Stale','قديم'],
  ['Back','السابق'],
  ['Next','التالي'],
  ['Done','تم'],
  ['Change','تغيير'],
  ['Suggested next','الخطوة المقترحة'],
  ['Continue story','كمّل القصة'],
  ['Open','فتح'],
  ['Close','إغلاق'],
  ['Export report','تصدير التقرير'],
  ['All screens map','خريطة كل الشاشات'],
  ['Explore freely','استكشف براحتك'],
  ['Recommended','مقترح'],
  ['Step','خطوة']
];

// Reverse/pure-English phrases. Existing i18n still does most translation; this
// list closes gaps left by mixed demo data and also reverses our Arabic labels
// when the language is switched without a full reload.
const toEnglish=[
  ['نسخة دوّر التجريبية','Dawwar Pilot'],
  ['النسخة التجريبية الأولى','Pilot MVP'],
  ['مساحة عمل تبدأ بالنسخة التجريبية','Pilot-first workspace'],
  ['عرض تفاعلي للمنتج','Interactive Product Demo'],
  ['الرؤية المستقبلية','Future Vision'],
  ['رؤية المنتج','Product Vision'],
  ['نموذج العمل','Business model'],
  ['إيراد الإطلاق','Launch revenue'],
  ['خارج نطاق الإطلاق','Not launch scope'],
  ['نطاق الإطلاق','Launch scope'],
  ['وعدنا للعميل','Customer promise'],
  ['وعدنا للقاعة','Venue promise'],
  ['سوق موثوق للقاعات','Trusted venue marketplace'],
  ['التوافر أولًا','Availability first'],
  ['طلب حجز','Request booking'],
  ['تحديد مصدر الحجز','Booking attribution'],
  ['تأكيد العميل','Customer confirmation'],
  ['تأكيد القاعة','Venue confirmation'],
  ['تسوية العمولات','Commission reconciliation'],
  ['عمولة النجاح','Success commission'],
  ['عمولة عند النجاح فقط','Commission only'],
  ['كشف العمولات','Commission statement'],
  ['كشف عمولات القاعة','Venue commission statement'],
  ['قادمة من المنصة','Platform-sourced'],
  ['عميل محتمل مؤهل','Qualified lead'],
  ['عملاء محتملون مؤهلون','Qualified leads'],
  ['عملاء محتملون مفتوحون','Open leads'],
  ['عميل محتمل جديد','New lead'],
  ['إدارة العملاء المحتملين','Leads CRM'],
  ['مسار العملاء المحتملين','Lead pipeline'],
  ['زمن الاستجابة للعملاء المحتملين','Lead response SLA'],
  ['زيارة محددة','Visit scheduled'],
  ['عرض / حجز مؤقت','Offer / Hold'],
  ['حجز سريع','Quick booking'],
  ['حجز خارجي','Offline booking'],
  ['حجز إلكتروني','Online booking'],
  ['إلكتروني + خارجي','Online + offline'],
  ['المخزون الإلكتروني','Online inventory'],
  ['المخزون الخارجي','Offline inventory'],
  ['التوافر الإلكتروني','Online availability'],
  ['التوافر الخارجي','Offline availability'],
  ['الدفع الإلكتروني','Online payment'],
  ['العربون الإلكتروني','Online deposit'],
  ['إدارة عمليات الدفع','Payment orchestration'],
  ['طبقة المعاملات','Transaction layer'],
  ['حجز مؤقت محمي من التعارض','Atomic hold'],
  ['الحجوزات المؤقتة الملزمة','Hard holds'],
  ['حجز مؤقت ملزم','Hard hold'],
  ['إدارة الاستردادات ومستحقات القاعات','Refund / payout orchestration'],
  ['الاستردادات / مستحقات القاعات','Refunds / payouts'],
  ['الحجوزات والمدفوعات','Bookings & Payments'],
  ['الباقات والأسعار','Packages & Pricing'],
  ['قواعد التسعير الديناميكي','Dynamic Pricing Rules'],
  ['التسعير الديناميكي','Dynamic Pricing'],
  ['تحليلات متقدمة','Premium analytics'],
  ['تحليلات السوق','Marketplace Intelligence'],
  ['صحة السوق','Marketplace Health'],
  ['نظرة عامة على المنصة','Platform Overview'],
  ['إدارة المنصة','Platform Admin'],
  ['تشغيل القاعات','Venue Operations'],
  ['طابور التحقق','Verification queue'],
  ['فحوصات التحقق','Verification checks'],
  ['صحة التقويم','Calendar Health'],
  ['درجة صحة التقويم','Calendar Health Score'],
  ['موثوقية التوافر','Availability Reliability'],
  ['مزامنة التوافر','Availability Sync'],
  ['توافر قديم','Stale availability'],
  ['توافر حديث','Fresh availability'],
  ['محدّث حديثًا','Recently updated'],
  ['كل الأنظمة تعمل','All systems operational'],
  ['خريطة الطلب','Demand heatmap'],
  ['فجوة العرض','Supply gap'],
  ['إيراد مفقود','Lost revenue'],
  ['طلب مفقود','Lost demand'],
  ['ذكاء الإيرادات','Revenue Intelligence'],
  ['ذكاء الأعمال','Business Intelligence'],
  ['مركز الإجراءات','Action Center'],
  ['محاكي الأسعار','Pricing Simulator'],
  ['المحاكي الاستراتيجي','Strategic Simulator'],
  ['تواريخ مرنة','Flexible Dates'],
  ['قائمة الأسرة المختصرة','Family Shortlist'],
  ['السوق العكسي','Reverse Marketplace'],
  ['اطلب عروضًا','Request Offers'],
  ['تواريخ متاحة في اللحظة الأخيرة','Last-minute inventory'],
  ['توافر مباشر','Live availability'],
  ['محاكاة عرض مباشر','Live deal simulation'],
  ['حجز ذكي','Smart booking'],
  ['بديل ذكي','Smart alternative'],
  ['أفضل قيمة','Best value'],
  ['يوم مرتفع الطلب','Peak demand date'],
  ['مصدر العميل المحتمل','Venue lead source'],
  ['فكرة لصاحب القاعة','Venue-side idea'],
  ['قاعات مناسبة فقط','Qualified supply only'],
  ['صلاحية العرض','Offer expiry'],
  ['مقارنة العروض','Offer comparison'],
  ['جودة المحتوى','Content Quality'],
  ['تحسن التحويل','Conversion lift'],
  ['درجة جودة الجولة','Tour quality score'],
  ['اكتمال الجولة','Tour completion'],
  ['مشاهد متعددة','Multiple scenes'],
  ['إدارة نقاط المعلومات','Hotspot management'],
  ['قائمة اكتمال التغطية','Coverage checklist'],
  ['الإيراد لكل تاريخ متاح','Revenue per Available Date'],
  ['ربحية الباقات','Package profitability'],
  ['توقع التدفق النقدي','Cash-flow forecast'],
  ['مبالغ مستحقة التحصيل','Outstanding receivables'],
  ['هامش المساهمة','Contribution margin'],
  ['ربح المساهمة','Contribution profit'],
  ['الربح التشغيلي','Operating profit'],
  ['هامش الربح','Profit margin'],
  ['مزيج الإيرادات','Revenue mix'],
  ['تكلفة اكتساب العميل','Customer CAC'],
  ['قيمة العميل','Customer LTV'],
  ['تكلفة اكتساب القاعة','Venue acquisition cost'],
  ['مدة استرداد تكلفة القاعة','Venue payback'],
  ['البحث بلا نتائج','Zero-result search'],
  ['نسبة فشل الدفع','Payment failure rate'],
  ['نسبة عدم تطابق التوافر','Availability mismatch rate'],
  ['نسبة الإلغاء','Cancellation rate'],
  ['نسبة الاسترداد','Refund rate'],
  ['نسبة النزاعات','Dispute rate'],
  ['تجاوزات زمن الخدمة','SLA breaches'],
  ['رحلة العميل التجريبية','Customer pilot'],
  ['تشغيل النسخة التجريبية','Pilot Ops'],
  ['إدارة وتشغيل النسخة التجريبية','Admin / Ops Pilot'],
  ['إدارة القاعات المبسطة','VenueOS Lite'],
  ['إدارة القاعات الاحترافية','VenueOS Pro'],
  ['نظام إدارة القاعات','VenueOS'],
  ['السوق','Marketplace'],
  ['تحقيق الإيرادات','Monetization'],
  ['ميزة تنافسية','Differentiation'],
  ['بيانات تشغيل فعلية','Production events'],
  ['مسار التحويل الأساسي','Core funnel'],
  ['العائد التشغيلي','ROI'],
  ['قابلة للتعديل والإصدار','Configurable/versioned'],
  ['قابلة للتعديل','Configurable'],
  ['مثبتة داخل النظام','Hard-coded'],
  ['تحديد المصدر','Attribution'],
  ['التسوية','Reconciliation'],
  ['حداثة البيانات','Freshness'],
  ['المدفوعات','Payments'],
  ['الاستردادات','Refunds'],
  ['مستحقات القاعات','Payouts'],
  ['اشتراك','Subscription'],
  ['العمولة','Commission'],
  ['استفسار','Enquiry'],
  ['عرض سعر','Quote'],
  ['عميل محتمل','Lead'],
  ['عملاء محتملون','Leads'],
  ['التقويم','Calendar'],
  ['الحجوزات','Bookings'],
  ['الحجز','Booking'],
  ['الزيارات','Visits'],
  ['زيارة','Visit'],
  ['البحث','Search'],
  ['القائمة المختصرة','Shortlist'],
  ['مقارنة','Compare'],
  ['إتمام الحجز','Checkout'],
  ['التوافر','Availability'],
  ['متاح','Available'],
  ['محجوز','Booked'],
  ['تأكيد مطلوب','Confirmation needed'],
  ['مؤكد','Confirmed'],
  ['العميل','Customer'],
  ['صاحب القاعة','Venue Owner'],
  ['القاعة','Venue'],
  ['المستثمر','Investor'],
  ['الإدارة','Admin'],
  ['التحليلات','Analytics'],
  ['الإيرادات','Revenue'],
  ['نسبة الإشغال','Occupancy'],
  ['التحويل','Conversion'],
  ['الحالة','Status'],
  ['التفاصيل','Details'],
  ['الرئيسية','Home'],
  ['استكشف','Explore'],
  ['الحساب','Account'],
  ['الدليل','Guide'],
  ['إعادة العرض التجريبي','Reset Demo'],
  ['النسخة التجريبية','Pilot'],
  ['عرض تجريبي','Demo'],
  ['النسخة الأولى','MVP'],

  ['رويال جاردن','Royal Garden'],
  ['لوما هول','Luma Hall'],
  ['نايل بالاس','Nile Palace'],
  ['جاردن 37','Garden 37'],
  ['بالم بالاس','Palm Palace'],
  ['ليك هاوس','Lake House'],
  ['باقة الزفاف المميزة','Wedding Plus'],
  ['القاعة فقط','Hall Only'],
  ['الباقة الخاصة','Signature'],

  ['غرفة العروس','Bridal room'],
  ['مسرح كبير','Large stage'],
  ['إطلالة على النيل','Nile view'],
  ['إطلالة على البحيرة','Lake view'],
  ['خارجي','Outdoor'],
  ['داخلي','Indoor'],
  ['موقف سيارات','Parking'],
  ['مسرح','Stage'],
  ['حديقة','Garden'],
  ['نظام صوت','Sound'],
  ['خدمة صف السيارات','Valet'],
  ['بوفيه','Buffet'],
  ['تجهيزات وزينة','Decoration'],

  ['محمود وسلمى','Mahmoud & Salma'],
  ['كريم وآية','Mahmoud & Salma'],
  ['منى وعلي','Mona & Ali'],
  ['عمر ومريم','Omar & Mariam'],
  ['نور وأحمد','Nour & Ahmed'],
  ['سارة ومصطفى','Sara & Mostafa'],
  ['هنا ويوسف','Hana & Youssef'],
  ['يارا وآدم','Yara & Adam'],

  ['القاهرة الجديدة','New Cairo'],
  ['الشيخ زايد','Sheikh Zayed'],
  ['مدينة نصر','Nasr City'],
  ['المعادي','Maadi'],
  ['أكتوبر','October'],
  ['سبتمبر','September'],
  ['الضيوف','Guests'],
  ['ضيوف','guests'],
  ['الميزانية','Budget'],
  ['التاريخ','Date'],
  ['المنطقة','Area'],
  ['نوع المناسبة','Event type'],
  ['زفاف','Wedding'],
  ['خطوبة','Engagement'],
  ['مناسبة شركات','Corporate event'],
  ['سعر مبدئي','Starting price'],
  ['القيمة النهائية للقاعة','Final venue value'],
  ['العربون','Deposit'],
  ['تم الاستلام','Received'],
  ['مستحقة','DUE'],
  ['تم الحجز','Won'],
  ['استفسارات معلقة','Pending enquiries'],
  ['قاعات موثقة','Verified venues'],
  ['قاعة موثقة','Verified venue'],
  ['موثقة','Verified'],
  ['حديث','Fresh'],
  ['قديم','Stale'],
  ['السابق','Back'],
  ['التالي','Next'],
  ['تم','Done'],
  ['تغيير','Change'],
  ['الخطوة المقترحة','Suggested next'],
  ['كمّل القصة','Continue story'],
  ['فتح','Open'],
  ['إغلاق','Close'],
  ['تصدير التقرير','Export report'],
  ['خريطة كل الشاشات','All screens map'],
  ['استكشف براحتك','Explore freely'],
  ['مقترح','Recommended'],
  ['خطوة','Step'],
  ['ج.م','EGP']
];

function replaceAll(text,pairs){
  let out=text;
  for(const [from,to] of pairs){
    if(out.includes(from))out=out.split(from).join(to);
  }
  return out;
}

function arabicNumericCleanup(text){
  return text
    .replace(/(\d+(?:\.\d+)?)K\b/g,'$1 ألف')
    .replace(/(\d+(?:\.\d+)?)M\b/g,'$1 مليون')
    .replace(/\bEGP\b/g,'ج.م');
}

function englishNumericCleanup(text){
  return text
    .replace(/[٠-٩]/g,d=>ARABIC_DIGITS[d]||d)
    .replace(/(\d+(?:\.\d+)?)\s*ألف/g,'$1K')
    .replace(/(\d+(?:\.\d+)?)\s*مليون/g,'$1M')
    .replace(/ج\.م/g,'EGP');
}

function purifyText(text){
  if(!text||!text.trim())return text;
  if(currentLanguage()==='en')return englishNumericCleanup(replaceAll(text,toEnglish));
  return arabicNumericCleanup(replaceAll(text,toArabic));
}

function localizeBrand(root=document){
  const ar=currentLanguage()!=='en';
  document.documentElement.lang=ar?'ar':'en';
  document.documentElement.dir=ar?'rtl':'ltr';
  document.querySelectorAll('.brand span:last-child,.dawwar-brand-word').forEach(el=>{el.textContent=ar?'دوّر':'Dawwar'});
  document.querySelectorAll('.brand-mark').forEach(el=>{el.textContent=ar?'د':'D'});
  document.querySelectorAll('.brand').forEach(el=>el.setAttribute('aria-label',ar?'دوّر':'Dawwar'));
  if(document.title)document.title=ar?'دوّر | عرض تفاعلي للمنتج':'Dawwar | Interactive Product Demo';
}

let applying=false;
function apply(root=document){
  if(applying)return;
  applying=true;
  try{
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
    const nodes=[];
    while(walker.nextNode())nodes.push(walker.currentNode);
    for(const node of nodes){
      if(node.parentElement?.closest('script,style,code,pre'))continue;
      const next=purifyText(node.nodeValue);
      if(next!==node.nodeValue)node.nodeValue=next;
    }
    localizeBrand(root);
  }finally{applying=false;}
}

let timer;
function schedule(){clearTimeout(timer);timer=setTimeout(()=>apply(document.body),40);}
const observer=new MutationObserver(schedule);

function start(){
  apply(document.body);
  observer.observe(document.body,{subtree:true,childList:true,characterData:true});
}

global.dawwarPurifyLanguage=apply;
global.dawwarPurifyText=purifyText;
global.addEventListener('hashchange',schedule);
global.addEventListener('hh:languagechange',()=>setTimeout(()=>apply(document.body),80));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})(window);
