const fs=require('fs');const assert=require('assert');
const index=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('navigator.js','utf8');
const css=fs.readFileSync('navigator.css','utf8');
for(const f of ['navigator.css','navigator.js'])assert(index.includes(f),`index missing ${f}`);
for(const id of ['full','customer','venue','admin','investor'])assert(js.includes(`${id}:`),`tour missing: ${id}`);
for(const route of ['venue/royal-garden','pilot/request/royal-garden','pilot/quote/royal-garden','pilot/confirmed','pilot/commission','pilot/ops','admin/verification','vision','investor'])assert(js.includes(`'${route}'`),`guided route missing: ${route}`);
for(const fn of ['hhOpenDemoNavigator','hhStartTour','hhTourNext','hhTourBack','hhTakeSmartNext','hhResetGuidedDemo','hhStopTour'])assert(js.includes(fn),`global action missing: ${fn}`);
assert(js.includes('hh:languagechange'),'navigator must react to language changes');
assert(js.includes('Dawwar Pilot'),'navigator must present pilot-first story');
assert(js.includes('Request-to-Book'),'navigator must use request-to-book as launch conversion path');
assert(js.includes('success commission'),'venue tour must explain launch monetization');
assert(css.includes('@media(max-width:760px)'),'mobile navigator styles missing');
assert(css.includes('@media(prefers-reduced-motion:reduce)'),'reduced motion support missing');
console.log('Dawwar demo navigator tests passed');
